# === 1. Data Download Configuration ===
download_data: True   # Set to true to download fresh data, false to skip
station_id: ''
lookback: 8        # Number of past days to consider for prediction
# === 2. Date Ranges ===
dates:
  train:
    start: '1990-01-01'
    end: '2017-03-23'
  test:
    start: '2017-03-24'
    end: '2023-12-31'
  predict:
    start: '2024-01-01'
    end: '2024-12-31'
# ===3. Filling of missing values
filling_parameters:
  type: 'smart'        # filling missing data by either 'climatology', 'interpolate' or 'smart'
  gap_threshold: 4     # if type is smart then if continuous gap below gap_threshold will be filled by interpolation if above gap_threshold will use climatology
# === 4. Scaling Configuration ===
scaling:
  wind_threshold_percent: 95  # Threshold percentile for wind magnitude

# === 5. Hyperparameter Optimization and Cross Validation ===
hyper_optim:
  device: "cuda"           # "cpu" or "cuda"
  n_trials: 200            # number of trials for each run
  njobs: 4                 # parallel jobs ('cpu' only)
  physics_mode: both       # options: none | with | both
  val_size: 10             # validation size (%)
  k_folds: 7               # CV folds
  epochs: 300
  es_patience: 25
  

  search_space:
    hidden_size:
      type: int
      low: 1
      high: 130
      step: 1
    num_layers:
      type: int
      low: 1
      high: 3
      step: 1
    learning_rate:
      type: float
      low: 1e-4
      high: 0.1
      log: true
    weight_decay:
      type: float
      low: 1e-4
      high: 1.0
      log: true
    lambda_physics:
      type: float
      low: 1e-4
      high: 10.0
      log: true
  rank: 'all'  # 'all' |list of ranks e.g. [1,3,5]| tuple (start, end, step) e.g. (1,12,2)
# === 6. Training Model Configuration ===
training:
  mode: 'single'  # 'single' or 'ensemble'
  use_rank: true  # If true, 'rank' below will be used. If false, use individual params below.
  rank: 1  # If mode is 'single' and use_rank is true, use int. 
                  #if mode is 'ensemble' use tuple (start, end, step) or list 
                  
  hold_out: 12  # percentage of data to hold out for early stopping
  epochs: 500
  es_patience: 25 # early stopping patience for hold_out set
  device: "cuda"           # "cpu" or "cuda" for gpu

  # Used only if 'use_rank' is false and 'single' mode is selected
  params:
    learning_rate: 0.0005
    weight_decay: 0.0005
    hidden_size: 64
    num_layers: 2
    lambda_physics: 1.25
  B: 1200  # Bootstrap samples for uncertainty for 'ensemble' mode
  low: 2.5  # Lower percentile for uncertainty for 'ensemble' mode
  high: 97.5  # Upper percentile for uncertainty 'ensemble' mode

# === 8. Prediction Toggle ===
prediction:
  run_prediction: true  # Set to true for predicting on unseen data, false to skip
  device: "cuda"           # "cpu" or "cuda"
  B: 1000  # Bootstrap samples for uncertainty for 'ensemble' mode
  low: 2.5  # Lower percentile for uncertainty for 'ensemble' mode
  high: 97.5  # Upper percentile for uncertainty 'ensemble' mode
